substitutions:            # Keller Verteilerschrank
  device_name: esp32-02

esphome:
  name: ${device_name}

external_components:
  - source:
      type: local
      path: components

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:

api:
  encryption:
    key: 

ota:
  - platform: esphome
    password: 

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "${device_name} Hotspot"
    password: "RNJfuP9fC7qe"

captive_portal:


mqtt:
  broker: 10.0.0.21
  username: mqtt
  password: mqtt
  discovery: false

  on_message:
    - topic: "dimmer/dimm_script02"
      payload: "pressed02"
      then:
        - lambda: id(dim_control02).publish_state(true);
        - script.execute:
            id: dimm_script02
            target_light: light02
            trigger_binary: dim_control02
    - topic: "dimmer/dimm_script02"
      payload: "released02"
      then:
        - lambda: id(dim_control02).publish_state(false);

    - topic: "dimmer/dimm_script03"
      payload: "pressed03"
      then:
        - lambda: id(dim_control03).publish_state(true);
        - script.execute:
            id: dimm_script03
            target_light: light03
            trigger_binary: dim_control03
    - topic: "dimmer/dimm_script03"
      payload: "released03"
      then:
        - lambda: id(dim_control03).publish_state(false);

script:
  - id: dimm_script02
    parameters:
      target_light: esphome::light::LightState*
      trigger_binary: esphome::binary_sensor::BinarySensor*
    mode: restart
    then:
      - delay: 0.8s 
      - while:
          condition:
            lambda: return trigger_binary->state;
          then:
            - lambda: |-
                if (target_light == nullptr || trigger_binary == nullptr) return;         
                float current_b = target_light->remote_values.get_brightness();
                static bool dim_up = true; 
                if (current_b < 0.05f) dim_up = true;
                else if (current_b > 0.95f) dim_up = false;

                float step = dim_up ? 0.02f : -0.02f;
                float new_brightness = current_b + step;
                
                if (new_brightness > 1.0f) new_brightness = 1.0f;
                if (new_brightness < 0.01f) new_brightness = 0.01f;

                auto call = target_light->make_call();
                call.set_brightness(new_brightness);
                call.set_state(true);
                call.set_transition_length(100);
                call.perform();
            - delay: 0.1s

  - id: dimm_script03
    parameters:
      target_light: esphome::light::LightState*
      trigger_binary: esphome::binary_sensor::BinarySensor*
    mode: restart
    then:
      - delay: 0.8s 
      - while:
          condition:
            lambda: return trigger_binary->state;
          then:
            - lambda: |-
                if (target_light == nullptr || trigger_binary == nullptr) return;
                float current_b = target_light->remote_values.get_brightness();
                static bool dim_up = true; 
                if (current_b < 0.05f) dim_up = true;
                else if (current_b > 0.95f) dim_up = false;

                float step = dim_up ? 0.02f : -0.02f;
                float new_brightness = current_b + step;
                
                if (new_brightness > 1.0f) new_brightness = 1.0f;
                if (new_brightness < 0.01f) new_brightness = 0.01f;

                auto call = target_light->make_call();
                call.set_brightness(new_brightness);
                call.set_state(true);
                call.set_transition_length(100);
                call.perform();
            - delay: 0.1s

i2c:
  - id: bus_a
    sda: GPIO21
    scl: GPIO22
    scan: true

pcf8574:
  - id: i2c_relay05
    address: 0x27
    pcf8575: True
    i2c_id: bus_a

  - id: i2c_relay04
    address: 0x3B
    pcf8575: false
    i2c_id: bus_a



mcp23017:
  - id: i2c_expand06
    address: 0x20
    i2c_id: bus_a

power_supply:
  
  - id: i2c_relay05_sw07          # Wandlicht Keller/Stiege
    keep_on_time: 0.5s
    enable_time: 0.5s
    pin:
      pcf8574: i2c_relay05
      number: 7
      inverted: true

  - id: i2c_relay05_sw02          # Wohnraum Keller
    keep_on_time: 0.5s
    enable_time: 0.5s
    pin:
      pcf8574: i2c_relay05
      number: 2
      inverted: true



output:

# Dimmer Wandlicht Keller/Stiege
  - platform: i2c_dimmer                 
    address: 0x11
    id: dimmer_output00
    power_supply: i2c_relay05_sw07
    min_power: 0.25
    max_power: 0.7

# Dimmer Wohnraum Keller
  - platform: i2c_dimmer                 
    address: 0x10
    id: dimmer_output01
    power_supply: i2c_relay05_sw02
    min_power: 0.18
    max_power: 0.7

# Garagentor
  - platform: gpio
    id: gt
    pin:
      pcf8574: i2c_relay04
      number: 4
      mode:
         output: true
    inverted: true

# Türöffner EG
  - platform: gpio
    id: do_01
    pin:
      pcf8574: i2c_relay04
      number: 5
      mode:
         output: true
    inverted: true

light:
# Dimmer Wandlicht Keller/Stiege
  - platform: monochromatic
    id: light02
    name: "light02"
    gamma_correct: 2
    output: dimmer_output00
    icon: mdi:wall-sconce-round-variant-outline

          
# Dimmer Wohnraum Keller
  - platform: monochromatic
    id: light03
    name: "light03"
    output: dimmer_output01
    icon: mdi:chandelier

button:

  - platform: restart
    name: '${device_name} Restart'
    internal: false

  - platform: output
    name: "Garage Tor"
    id: garage_tor
    icon: mdi:gesture-tap-button
    output: gt
    duration: 300ms

  - platform: output
    name: "Door EG"
    id: door_eg
    icon: mdi:gesture-tap-button
    output: do_01
    duration: 3s

switch:

  - platform: gpio                  # Touchscreen EG
    name: "power_touch_eg" 
    id: power_touch_eg
    pin:
      pcf8574: i2c_relay04
      number: 7
      mode:
         output: true
    inverted: true

  - platform: gpio
    name: "i2c_relay05_sw01"          # Wandlicht Bad Keller
    id: i2c_relay05_sw01
    icon: mdi:coach-lamp-variant
    pin:
      pcf8574: i2c_relay05
      number: 1
      mode:
        output: true
    inverted: true

  - platform: gpio
    name: "i2c_relay05_sw03"          # Boden- Wandspots Bad Keller
    id: i2c_relay05_sw03
    icon: mdi:light-flood-down
    pin:
      pcf8574: i2c_relay05
      number: 3
      mode:
        output: true
    inverted: true

  - platform: gpio                    # Speis
    name: "i2c_relay05_sw04"
    id: i2c_relay05_sw04
    icon: mdi:ceiling-light-outline
    pin:
      pcf8574: i2c_relay05
      number: 4
      mode:
        output: true
    inverted: true

  - platform: gpio                   # WC Keller
    name: "i2c_relay05_sw05"
    id: i2c_relay05_sw05
    icon: mdi:ceiling-light-outline
    pin:
      pcf8574: i2c_relay05
      number: 5
      mode:
        output: true
    inverted: true

  - platform: gpio                  # Bodenspots Keller/Stiege
    name: "i2c_relay05_sw06"
    id: i2c_relay05_sw06
    icon: mdi:light-flood-down
    pin:
      pcf8574: i2c_relay05
      number: 6
      mode:
        output: true
    inverted: true

  - platform: gpio                   # Gästezimmer
    name: "i2c_relay05_sw08"
    id: i2c_relay05_sw08
    icon: mdi:chandelier
    pin:
      pcf8574: i2c_relay05
      number: 8
      mode:
        output: true
    inverted: true

  - platform: gpio                 #  Bodenspots EG OG
    name: "i2c_relay05_sw09"
    id: i2c_relay05_sw09
    icon: mdi:light-flood-down
    pin:
      pcf8574: i2c_relay05
      number: 9
      mode:
        output: true
    inverted: true

  - platform: gpio                  # EG Windfang
    name: "i2c_relay05_sw10"
    id: i2c_relay05_sw10
    icon: mdi:coach-lamp-variant
    pin:
      pcf8574: i2c_relay05
      number: 10
      mode:
        output: true
    inverted: true

  - platform: gpio                  # Aussenlicht Eingang EG
    name: "i2c_relay05_sw11"
    id: i2c_relay05_sw11
    icon: mdi:outdoor-lamp
    pin:
      pcf8574: i2c_relay05
      number: 11
      mode:
        output: true
    inverted: true

  - platform: gpio                  #  WC EG
    name: "i2c_relay05_sw12"
    id: i2c_relay05_sw12
    icon: mdi:ceiling-light-outline
    pin:
      pcf8574: i2c_relay05
      number: 12
      mode:
        output: true
    inverted: true

  - platform: gpio
    name: "i2c_relay05_sw13"         # Garage Licht
    id: i2c_relay05_sw13
    icon: mdi:lightbulb-fluorescent-tube-outline
    pin:
      pcf8574: i2c_relay05
      number: 13
      mode:
        output: true
    inverted: true

  - platform: gpio
    name: "i2c_relay05_sw14"         # Keller Windfang
    id: i2c_relay05_sw14
    icon: mdi:ceiling-light-outline
    pin:
      pcf8574: i2c_relay05
      number: 14
      mode:
        output: true
    inverted: true


sensor:

  - platform: dht
    model: dht22
    pin: GPIO25
    temperature:
      name: "Temp K Wohnraum"
      filters:
       - offset: 2
    humidity:
      name: "Humidity K Wohnraum"
      filters:
       - offset: 1
    update_interval: 50s
  
  - platform: wifi_signal
    name: "WiFi Signal ${device_name}"
    update_interval: 60s


binary_sensor:
  - platform: template
    id: dim_control02
    internal: true

  - platform: template
    id: dim_control03
    internal: true


  - platform: gpio            # Tür Eingang K oben
    name: "bin_sens_61"
    id: bin_sens_61
    pin:
      mcp23xxx: i2c_expand06
      number: 1
      mode:
        input: true
        pullup: true
      inverted: true
    device_class: light
    on_multi_click:

    - timing:
        - ON for at most 0.3s
        - OFF for at most 0.3s
        - ON for at most 0.3s
        - OFF for at least 0.5s        
      then:
      - switch.toggle: i2c_relay05_sw06

    - timing:
        - ON for at most 0.3s
        - OFF for at least 0.6s
      then:
        - if:
            condition:
              light.is_off: light02
            then:
              light.turn_on: 
                id: light02
                brightness: 0.4
            else:
              light.turn_off: light02

    on_press:
      then:
        - script.execute:
            id: dimm_script02
            target_light: light02
            trigger_binary: bin_sens_61
    

  - platform: gpio           #   Tür Eingang K unten
    name: "bin_sens_62"
    id: bin_sens_62
    pin:
      mcp23xxx: i2c_expand06
      number: 2
      mode:
        input: true
        pullup: true
      inverted: true
    device_class: light
    on_multi_click:
    - timing:
        - ON for at most 0.4s
        - OFF for at least 0.6s
      then:
        - switch.toggle: i2c_relay05_sw11
    - timing:
        - ON for 0.4s to 1s
        - OFF for at least 0.6s
      then:
        - switch.toggle: i2c_relay05_sw14

  - platform: gpio                # WR K Tür oben
    name: "bin_sens_63"
    id: bin_sens_63
    pin:
      mcp23xxx: i2c_expand06
      number: 3
      mode:
        input: true
        pullup: true
      inverted: true
    device_class: light
    on_multi_click:

    - timing:
        - ON for at most 0.3s
        - OFF for at most 0.3s
        - ON for at most 0.3s
        - OFF for at least 0.4s        
      then:
        - homeassistant.service:
             service: cover.stop_cover
             data:
               entity_id: cover.rollo_keller
    - timing:
        - ON for at most 0.3s
        - OFF for at most 0.3s
        - ON for 0.3s to 0.8s
        - OFF for at least 0.4s
      then:
        - homeassistant.service:
             service: cover.close_cover
             data:
               entity_id: cover.rollo_keller
    - timing:
        - ON for at most 0.3s
        - OFF for at most 0.3s
        - ON for 0.8s to 1.4s
        - OFF for at least 0.4s
      then:
        - homeassistant.service:
             service: cover.open_cover
             data:
               entity_id: cover.rollo_keller

    - timing:
        - ON for at most 0.3s
        - OFF for at least 0.6s
      then:
        - if:
            condition:
              light.is_off: light03
            then:
              light.turn_on: 
                id: light03
                brightness: 0.4
            else:
              light.turn_off: light03

    on_press:
      then:
        - script.execute:
            id: dimm_script03
            target_light: light03
            trigger_binary: bin_sens_63

  - platform: gpio              # Vorraum K Tür WR R
    name: "bin_sens_64"
    id: bin_sens_64
    pin:
      mcp23xxx: i2c_expand06
      number: 4
      mode:
        input: true
        pullup: true
      inverted: true
    device_class: light
    on_multi_click:

    - timing:
        - ON for at most 0.3s
        - OFF for at least 0.6s
      then:
        - if:
            condition:
              light.is_off: light02
            then:
              light.turn_on: 
                id: light02
                brightness: 0.4
            else:
              light.turn_off: light02

    on_press:
      then:
        - script.execute:
            id: dimm_script02
            target_light: light02
            trigger_binary: bin_sens_64

  - platform: gpio            # Vorraum K Tür WR L
    name: "bin_sens_65"
    id: bin_sens_65
    pin:
      mcp23xxx: i2c_expand06
      number: 5
      mode:
        input: true
        pullup: true
      inverted: true
    device_class: light
    on_press:
        - switch.toggle: i2c_relay05_sw06

  - platform: gpio            # WR K Tür unten
    name: "bin_sens_66"
    id: bin_sens_66
    pin:
      mcp23xxx: i2c_expand06
      number: 6
      mode:
        input: true
        pullup: true
      inverted: true
    device_class: light
    on_multi_click:
    - timing:
        - ON for at most 0.3s
        - OFF for at least 0.6s
      then:
        - switch.toggle: i2c_relay05_sw01
